### PR TITLE
Add support for --password option

### PR DESCRIPTION
**Pull request by edpbx**
`git-svn` doesn't support yet but it will!

### CODE REVIEW

**Comment by edpbx** [comment]
@nirvdrum it would be really helpful if you could merge this so it's authoritative. `svn` itself supports it, and soon enough `git-svn` will.

**Comment by nirvdrum** [comment]
I take it's backwards-compatible?  No-op is fine.  I just don't want to raise exceptions on people running older versions of git-svn.

**Comment by edpbx** [comment]
It will cause some kind of problem if people specify a `--password` and installed svn doesn't support that. However, surely no harm done?

**Comment by edpbx** [comment]
Remember, that exception could only happen if people
* have a pre-2008 (at least) copy of SVN
* specify a `--password`

Is this really a problem? The error message will surely be very clear.

**Comment by nirvdrum** [comment]
That should be fine then.  I have a full matrix of versions I end up testing against.  Since Ubuntu 10.04 LTS is now rolling out of its support phase, that will bump a bunch of people up version-wise anyway.

Can you please make a documentation addition for the new option as well?

**Comment by edpbx** [comment]
@nirvdrum Done!

**Comment by nirvdrum** [comment]
Thanks!

**Comment by nirvdrum** [comment]
I'll try to take a pass through some other stuff this weekend and do a new release.

**Comment by edpbx** [comment]
:+1:

**Pull request merged**
