### PR TITLE
Adding missing libs to installation README

### PR DESCRIPTION
**Pull request by gpolak**

### CODE REVIEW

**Comment by edpbx** [comment]
On Ubuntu 12 this change is unnecessary. This PR seems obsolete?

**Comment by gpolak** [comment]
If it's in there on Ubuntu 12 and 14, then yeah, the PR is outdated. Feel free to can it.

**Comment by edpbx** [comment]
I can't, but you can - please could you click "Close"?

**Comment by gpolak** [comment]
Closing.

**Pull request closed without merging**
