### PR TITLE
Allow `tags` and `branches` arguments to be specified multiple times

### LINKED ISSUE #175: Allow multiple --branches and --tags options
This is a request for improvement, not a bug report.

The git-svn command allows for multiple --branches and --tags options but svn2git allows just one of each. It would be nice to drop this restriction.

I'm sorry, but I can't speak Ruby to provide a pull request. ;-)

### PR DESCRIPTION
**Pull request by pdf**
This mirrors upstream, though I'm not certain of which git-svn version this
functionality was added.

Fixes #175

The first commit (34ba3f3) just cleans up some lint to stop my editor
complaining, I can push without that if you don't want to take it.

### CODE REVIEW

**Comment by robinro** [comment]
@nirvdrum Please merge this, the feature is available in git-svn for quite some time and the implementation is backwards-compatible if one specifies only one --branch argument.

**Comment by nirvdrum** [comment]
Thanks. Do you happen to know when the feature was introduced? It'd be helpful to have for documentation. An updated example for the README would be nice as well, but could be added afterwards.

@pdf I'd prefer to merge without the linter fixes. Unfortunately, even the other commit sets off warnings over here because of silly things like the `{` in your iterator not being separated by a space. I can fix those up easily enough, but I'd rather avoid ping-ponging on style issues. If you can't push the branch without the lint fixes, I'll just cherry-pick the commit.

**Comment by pdf** [comment]
Lint commit removed, I think I had a cursory look through the upstream changelogs, but couldn't readily find when the functionality was introduced, but it was quite some time ago.

**Comment by robinro** [comment]
According to https://git-scm.com/docs/git-svn/1.8.0.3 the option to have multiple branches was already in 1.8 and the manpage history does not get any older. The oldest in-production git version I know is centos6 with 1.7.x, so any reasonable user will have this feature available.

**Comment by nirvdrum** [comment]
Great. Thanks for the follow-up. FYI, I usually use the oldest supported Ubuntu LTS as the lowest common denominator. In this case, that's 12.04, which ships with 1.7.9.5. That's not to say I'm opposed to adding newer features that require newer gits, but I don't want to add anything that will break for people currently using svn2git. This pull request seems backwards compatible, so I'm okay with it.

**Comment by robodude666** [comment]
+1 to request.

I can't find documentation for 1.7.9.5, but [git 1.7.7.2](https://git-scm.com/docs/git-svn/1.7.7.2) had support for multiple `--tags` or `--branches`.

**Pull request merged**
