### PR TITLE
Added --localtime to command line options

### PR DESCRIPTION
**Pull request by killsto**
This fixes issue #128

### CODE REVIEW

**Comment by andrasq** [comment]
I rebased it, see #185.

**Comment by edpbx** [comment]
@andrasq may I suggest closing this PR since it's now obsolete?

**Comment by andrasq** [comment]
obsolete how?

**Comment by nirvdrum** [comment]
Sorry, I completely missed the rebase update.  I'll take a look and see what the current status is here.

**Comment by edpbx** [comment]
@andrasq I mean that the functionality in *this* PR from you has merge conflicts and is available in your #185, so there is no reason to leave *this* PR open?

**Comment by andrasq** [comment]
@edpbx oh, right you are.  #185 is the same, yes; this can be closed

**Comment by edpbx** [comment]
Great! I'm not an admin of this: could you click the "close"? :-)

**Comment by andrasq** [comment]
oh!  I think you meant to ask @killsto, the author of #130.  I, @andrasq, rebased (duplicated really) the feature in #185, but 130 isn't mine to close.

**Comment by killsto** [comment]
I forgot I did this! I will go ahead and close it.

**Comment by edpbx** [comment]
:+1:

**Comment by jacobwwang** [comment]
@andrasq 
I run `svn2git --localtime --rebase`, based on => https://github.com/andrasq/svn2git
But the timestamp still is `Date:   Thu Jun 8 04:50:40 2017 +0000`
How can i fix it
Thanks

**Comment by andrasq** [comment]
what is your local computer timezone?  The `--localtime` option is just passed
to `git svn fetch --localtime`, which I think prevents the svn commit timestamps
from getting converted to GMT.  I don't know what happens if the svn timestamps
themselves are GMT; our repos had localtime svn commit times.

**Comment by jacobwwang** [comment]
@andrasq 
Thanks for your reply.
Both local computer timezone and svn commit timestamp are 'China Standard Time UT+8:00'.

It can correctly convert timestamp when I use `svn2git svn_url --localtime ` to create a git repo.

But I use `svn2git --rebase --localtime` to pull in the latest changes from SVN into my git repo created from above, it doesn't work. the timestamp of commit still is GMT+0000.

**Pull request closed without merging**
