### PR TITLE
Fix for git localized messages issue, and also fixes "gc is already running" message.

### PR DESCRIPTION
**Pull request by denixx**

### CODE REVIEW

**Comment by nirvdrum** [comment]
Thanks for this. Could you please squash the commits and remove the commit that increments the version number? I'll bump the version number when ready to release. Thanks!

**Comment by nirvdrum** [comment]
Looking again, you wrote some nice release notes. I can merge once the commits are squashed. I'll probably change the changelog text up a bit, but I can do that post merge.

**Comment by denixx** [comment]
Sorry, I was some kind of busy these days, will fix it now.

**Comment by pudge** [comment]
This solved the problem for me.  :+1: :shipit:

**Comment by denixx** [comment]
Closing this, made new fork :(
Got lost in squashing.
look at https://github.com/nirvdrum/svn2git/pull/216

**Pull request closed without merging**
