### PR TITLE
Fix for git localized messages issue, and also fixes "gc is already running" message.

### PR DESCRIPTION
**Pull request by denixx**
Sorry, I got lost in IDEA-vs-git battle and made changes from a new fork.
Now it's in one commit, maybe I'll get into squashing commits some day, but not today. :)

### CODE REVIEW

**Comment by denixx** [comment]
https://github.com/nirvdrum/svn2git/issues/180

**Review by Mattlk13 — APPROVED** [review]

**Review by Mattlk13 — APPROVED** [review]

**Comment by denixx** [comment]
Fixed conflict.

**Comment by nirvdrum** [comment]
Sorry to be such a bother, but can you rebase onto master to get rid of that merge commit?

**Comment by denixx** [comment]
Let me try to do that. :)

**Comment by denixx** [comment]
Ooops, I did it again...

**Pull request closed without merging**
